bind_to_address "127.0.0.1"
port "41122"

music_directory "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file "~/.config/mpd/db"
log_file "/tmp/logmpd"
pid_file "~/.config/mpd/pid"
state_file "~/.config/mpd/state"
auto_update "yes"
auto_update_depth "2"

audio_output {
	type "pulse" # or pulse,alsa
	name "default"
	options "software"
}

# fifo-вывод для визуализатора ncmpcpp (visualizer_data_source)
audio_output {
	type "fifo"
	name "Visualizer feed"
	path "/tmp/mpd.fifo"
	format "44100:16:2"
}
